apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: nour292/frontend-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - name: http
              containerPort: 7000
          # (Optionnel mais recommandé)
          readinessProbe:
            httpGet:
              path: /
              port: 7000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 7000
            initialDelaySeconds: 20
            periodSeconds: 20

