apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=   # base64 pour "postgres"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 pour "password"
  POSTGRES_DB: ZGF0YWJhc2U=       # base64 pour "database"
